FROM python:3.9.6-slim

RUN pip install pip --upgrade

COPY experiments/optuna_minikube experiments/optuna_minikube
COPY setup.py setup.py
COPY basht basht

RUN pip install -e .

CMD ["python", 'print("Hello World")']
