FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

RUN pip install pip --upgrade
RUN pip install ml_benchmark[test]==0.4.2

COPY test/test_ml_benchmark/workload/mnist/test_mlp_objective.py test_mlp_objective.py

CMD ["pytest", "-k", "test_mlp_objective_device[cuda]"]
