name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Install dependencies
      run: |
        pip install torch==1.11.0 torchvision==0.12.0
        pip install pylint
        pip install -e .["test"]
    - name: Test Package
      run: |
        pytest --cov=ml_benchmark test/
        pyreverse -o png ml_benchmark --output-directory docs
        echo $GITHUB_REF
